### ISSUE TITLE
skin default and npc invisable

### ISSUE THREAD

**Issue by Cammo009** [CitizensDev/Citizens2#223]
Hi Citizer, im am running a spigot 1.8 server and having issues with the citizen2 2.0.14 that some skins default to steve skin and sometimes the Npc's can disappear and not come back when out of chunk ratious and then return back. sometimes i cant see them when login in and have to relog 2 to 3 times.

when npc is invisable you can still select them. There is no error in console, just these smal issues.

Chris

**Comment by koatheraiser** [comment]
Same issue here,
Skins (no matter if set by name or by /npc skin) revert to default, unless I use /citizens reload, and that only works if the NPC is in my line of sight. No errors in console as well.

Running Spigot (spigot_1.8_899f5ee-1092acb) and the latest Dev of Citizens2.

Good luck. Love the plugin, would be great to see this working.

**Comment by CKGAR** [comment]
Confirmed.

**Comment by ZeTaurin** [comment]
I'm having this problem too, i'm using dtlTraders and players get so confused when the traders are not there all of a sudden.

**Comment by Apotheosis1337** [comment]
Its getting pretty annoying :/ Got the same problem as everyone else.. NPCs dissapearing or changing to default skin whenever they want. Dont let this plugin die.. if you have to transfer to Spigot and make it paid do it, but just let it die

**Comment by noorkoteb** [comment]
when will the next update be expected come out?

**Comment by mcmonkey4eva** [comment]
Our lead dev is MIA currently, working on waking him... I've personally no idea what to do with this bug, as I can't replicate it at all.

**Comment by gdude2002** [comment]
Can confirm this one - it seems that if the NPC is placed, it has the skin, but moving far enough away that it's unloaded client-side or changing world and coming back leaves it with the Steve skin

**Comment by pixelbat** [comment]
Experiencing this too. If mcmonkey4eva can't replicate it, I wonder what we all have in common, and if it's another plugin we have conflicting?

List of my plugins... AsyncWorldEdit, Citizens, CommunityBridge, Dynmap, Essentials, EssentialsChat, EssentialsSpawn, getUUID, Multiverse, Multiverse Portals, PermissionsEx, TimeShift, Titlemotd, WorldEdit, WorldGuard

**Comment by pixelbat** [comment]
Another thought... what version of Java are you folks running for your client? I only ask because I was using 8, then just went ahead and switched my client to use 7, and I haven't been able to replicate the issue yet.

**Comment by gdude2002** [comment]
@pixelbat I'm using Java 8 on both the client and server, as far as I can tell. Haven't  had a chance to test otherwise, though.

**Comment by pixelbat** [comment]
Spoke too soon, started happening with Java 7.

**Comment by noorkoteb** [comment]
well is there a way to save someones skin when they join and update it every 12hrs, because the problem is probably it trying to connect with the mojang servers due to 1.8 update. and with the saved skin it can just load from there and ignore mojang checks?

**Comment by gdude2002** [comment]
No, as far as I know, the client will only check Mojang's servers for updated skins.

Besides, as far as I know, it caches them until you restart the client.

**Comment by mcmonkey4eva** [comment]
Actually, in modern MC, the server is the one that pings Mojang's server for skin files, and it /does/ cache skins currently.

**Comment by gdude2002** [comment]
Huh, that seems like a new thing, then. When did they add that? lol

**Comment by mcmonkey4eva** [comment]
MC 1.7.6 was the first version to do this. It's also when issues like this one started appearing. This change in MC's code broke so much @.@

**Comment by noorkoteb** [comment]
that sucks is there anyway to get around it? will this ever be fixed?

**Comment by pixelbat** [comment]
No it will never get fixed because the devs can't replicate it, when the rest of the world can.

**Comment by gdude2002** [comment]
If the devs can't replicate it then there's something different in their testing environment.

Either way, I wouldn't dismiss them so easily - they make a great plugin, and are clearly trying their best.

**Comment by pixelbat** [comment]
@gdude2002 well the issue isn't exactly new. If you look at issues open and closed, it's been reported like over a dozen times, and dating as far back as Oct. It is a great plugin, but I find it hard to believe that this can't be replicated when so many other people can. Getting it replicated should be pretty easy with the assistance of the community. In the name of getting this fixed I'd be willing to share my server with the devs, where it is replicated.

**Comment by gdude2002** [comment]
Maybe it would be easier if @mcmonkey4eva could explain their testing environment?

**Comment by calico-kid** [comment]
i had this issue but it was due to an outdated plugin.... havnt had the issue since... it was caused by my essentials i had to update to the latest one for spigot... i am  running the latest on all builds and havnt had a problem since

**Comment by pixelbat** [comment]
@calico-kid hmmm, I also use Essentials. Are you using this version? https://hub.spigotmc.org/jenkins/job/Spigot-Essentials/

That's what I have and I'm having the issue. Are you using any of the other Essential plugins?

**Comment by calico-kid** [comment]
yeah thats the version i have... i dont use essentials anticheat or any of the others... i mainly only use it for warps atm since my server is in dev still might try removing the rest of the essentials kit and see if that changes anything... on a local test server of course...

**Comment by pixelbat** [comment]
Will give it a shot. I am using Essentials, Essentials Antibuild, Essentials Spawn, and Essentials Chat. Anyone else with the issue also using any of these 3 Essentials mods?

**Comment by gdude2002** [comment]
I'm using Essentials with Chat and Antibuild, yep.

**Comment by pixelbat** [comment]
Can't imagine Chat causing an issue, but maybe Antibuild. I don't even use it anymore, I'm gonna ditch it and see if that fixes my issue. I'll post back soon.

**Comment by calico-kid** [comment]
i would think more like spawn would be the major issuer... but antibuild could do it too

**Comment by CKGAR** [comment]
I have already confirmed it wasn't AntiBuild, and I'm running the same version as you guys. I am having a hard time believing this has anything to do with Essentials.

**Comment by calico-kid** [comment]
plugins do conflict at times... testing is important to be able to get a definite answer. twice now this has happened with different plugins for me both recently and early on @CKGAR

**Comment by CKGAR** [comment]
Ok, well if I'll go back to waiting patiently :P

**Comment by calico-kid** [comment]
i am wondering if someone else wants to try just having citizens and no other plugins to see if it does this... cuz i am thinking with the devs test servers its without other plugins... i know 3 that mcmonkey might hjave on there citizens denizen and depenizen prolly has WE and WG as well but idk if he has essentials or not

**Comment by CKGAR** [comment]
Wouldn't it be rather naïve and dumb to not have some of the widely used plugins like Essentials, mcMMO, Multiverse, etc. installed when trying to replicate? I mean really, it's easier one person do it than having tons of your users who run 40+ plugins isolate it..........

**Comment by calico-kid** [comment]
hey not my gig lol... i use denizen citizens and other plugins as well... multiverse hasnt caused any issues there was a cheat plugin that did and essentials did for me but thats been all thats caused any issue for me personally
and i dont code in java just throwing some suggestions out there cuz we need all the help we can get... mcmonkey oversees like 3 plugins at once and denizen is making some pretty heavy changes to maximize the speeds of it. @CKGAR

**Comment by Cammo009** [comment]
@pixelbat. Im running essentials snapshot with chat and spawn. I dont use anyother of there plugins.

**Comment by pixelbat** [comment]
Alright, so I loaded up a copy of my server locally with only Citizens. I also used an unmodded 1.8 client to make sure client side mods weren't contaminating what I see. I've also run both the server and my client with Java 7 and 8... and, it's still happening. Here is a video illustrating the issue... https://www.youtube.com/watch?v=7LKT-yGVqA8

Don't know what else to do. I've literally removed any chance for something to interfere. I also find it very difficult to believe that the plugin developer can't replicate this.

**Comment by CKGAR** [comment]
@pixelbat Ditto.

**Comment by calico-kid** [comment]
Seems as though this may be a respawn issue with the chuncks ill try it out again with all the latest build and see if i can replicate this... Is there anything else being used aside from base minecraft and citizens on your test servers? Eg forge or any other mods?

**Comment by pixelbat** [comment]
No.

**Comment by Apotheosis1337** [comment]
Same problem as well, i figured that the command /butcher removes NPCs which are <mobtype>

**Comment by noorkoteb** [comment]
this only happens to ppl who leave the npc when i tried this on my server my friend didn't move and he can still see the skin, but i left and came back i couldn't see the skins. when i disconnected and reconnected i could see it again. i believe this might be a communication issue with the players client.

**Comment by whoshenry** [comment]
Is this issue going to be fixed at all? I am still getting this issue even when using the latest Dev Build of Citizens 2.0.15 which claims the following: http://prntscr.com/6j1hl5

I am also using the latest ProtocolLIB so I'm not sure what's the issue here.

**Comment by mcmonkey4eva** [comment]
https://dl.dropboxusercontent.com/u/54130586/Citizens-2.0.15-SNAPSHOT.jar does this build help anyone else? Myself and another server owner are unable to replicate it in this build.

**Comment by whoshenry** [comment]
@mcmonkey4eva Still occurs on world change and when joining to begin with, using latest Spigot and ProtocolLIB.

**Comment by mcmonkey4eva** [comment]
@whoshenry protocollib isn't relevant. And try again, I updated the file in the link to catch a few more situations, including world change

**Comment by whoshenry** [comment]
@mcmonkey4eva This version you uploaded seems to be so much better. From constant world changing/flying around I've only experienced it a handful of times, but just going a little further away and coming back, they seem to load properly. I will keep testing it but this version is much better.

World changes seems to be fixed also. Just loads the skin a second or 2 after you have teleported which is perfectly fine.

**Comment by Cammo009** [comment]
@mcmonkey4eva

So what build do we need again for the fix? #1224

**Comment by mcmonkey4eva** [comment]
There are some problems on the current builds, use the Dropbox build linked above for the fix for now. In theory, the next successful build (IE, not marked with a red dot) will probably be functional too.

**Comment by mcmonkey4eva** [comment]
Update: #1227 is now functional

**Comment by Apotheosis1337** [comment]
Eh, I thought everything is fixed..
All of the latest dev builds dont work for 1.8
Thats why I updated Spigot to 1.8.3 .. But the skin gets removed again.. after teleporting away. ( Latest dev build. )

**Comment by mcmonkey4eva** [comment]
We build for latest, that's all there is to it. We're not going to maintain two separate versions of one plugin.
Also, can you provide some evidence that you're running latest dev build and still getting skin troubles? (EG, a video?) We need everything we can get if we're going to fix anything.

**Comment by Apotheosis1337** [comment]
Eh, I cant get a video tho.. But as much as I can
http://gyazo.com/ded2fdfaab50a24507ca11c3ac395785
http://gyazo.com/4ac9986f51fa246d73df015a9c604f03
http://imgur.com/T7wcHkc,3aVQWI7
The 2nd image was when I did /npc skin Notch
the 1st one, went 100 blocks away and came back to that.

**Comment by DNx5** [comment]
that's not #1227

**Comment by Apotheosis1337** [comment]
Indeed its not, but that version should have the fix as well.. I'll try 1227 right now!

**Comment by DNx5** [comment]
https://github.com/CitizensDev/Citizens2/commit/4d089155e4bf2d99f356c0eedb167311ba4ab440
^ that's the commit :D

**Comment by Apotheosis1337** [comment]
That commit was fixed in the 1227 wasnt it? If yes, still doesnt work.

**Comment by Morphan1** [comment]
@Apotheosis1337 maybe a video/some more pictures for it failing on 1227?

**Comment by BobLorodeth** [comment]
I have been experiencing this issue and after the best testing I could manage it seems there is a difference between chunk loading and world loading to the plugin. When I reload the world, e.g use a portal, disconnect, use a warp, or use a TP the NPCs lose their skins. However, when I fly/walk away and come back (which reloads the chunk) their skins return( sometimes a few at a time and sometimes all at once) 

Perhaps somebody would like to confirm my findings?

Hope this helps some,
-Bob

**Comment by whoshenry** [comment]
I know Mojang had some maintenance to their databases earlier, but it seems that ever since, I can't see any skins whatsoever. Tried reloading the plugin and the server, still can't see any skins. Maybe this will fix itself but did they change anything to do with fetching skins?

**Comment by Zerpixelt** [comment]
I have nearly the same problem, exept that I use "craftbukkit 1.7.9 R-0.2" and play with the "citizens 2.013" version. I can see capes, but I can't see any skins. And yes, I tried real playernames and also /npc skin (playername with skin), but nothing changed, just steves everywhere. I also deinstalled the whole server and put only citizens in the plugins-file, but also just ugly steves :P
Is there now any solution for this problem, because I need skins for my poor NPCs :(

**Comment by mcmonkey4eva** [comment]
Skins working at all well on 1.8.6?

**Comment by noorkoteb** [comment]
ill try it out

**Comment by THEBIGSEB** [comment]
Can u put the link of the Update: #1227 plz
